#!/usr/bin/env sh

#!/usr/bin/env sh

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ "$BRANCH" = "master" ]; then
  echo "❌ Direct commits to master are not allowed. Create a branch instead."
  exit 1
fi

# Your existing tasks
npm run fonts:extract && npm run content:compile
node ./scripts/compile-stylesheet.mjs
