name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'npm'

          # TODO: known bug with vite and roledown. omit the optional deps removal for now (npm ci --omit=optional)
      - name: Install & Build
        run: |
          npm ci
          npm run build # This runs your content compile + vite build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5